### ISSUE TITLE
Speech enhancement

### ISSUE THREAD

**Issue by mnabihali** [wangkenpu/Conv-TasNet-PyTorch#4]
Thanks for this useful repo.

I want to ask if I want to use it for speech enhancement I will put the noisy files as mix.scp and clean signals as s1.scp and the noise as s2.scp are it correct or not?

Another question how can I create a .scp file for my dataset?

**Comment by wangkenpu** [comment]
Please refer to [mix.scp](https://github.com/wangkenpu/Conv-TasNet-PyTorch/blob/master/data/cv/mix.scp).

The format is utterance_id TAB audio_path.
