### ISSUE TITLE
ImportError: No module named misc.logging

### ISSUE THREAD

**Issue by mnabihali** [wangkenpu/Conv-TasNet-PyTorch#5]
Dear 

When I am trying to run the code It gives me this Error
 No module named misc.logging
How can I solve this

**Comment by wangkenpu** [comment]
The module is [here](https://github.com/wangkenpu/Conv-TasNet-PyTorch/blob/master/utils/misc/logging.py). Please run the code according to the readme.

**Comment by mnabihali** [comment]
It seems that You don't add a description on the readme file only the results and requirements.

**Comment by wangkenpu** [comment]
Please refer to [README](https://github.com/wangkenpu/Conv-TasNet-PyTorch#usage). It tells you how to run.

**Comment by mnabihali** [comment]
[mnabih@moissan Co]$ scripts/run_tasnet.sh
-bash: scripts/run_tasnet.sh: Permission denied

**Comment by wangkenpu** [comment]
Please try to use `bash scripts/run_tasnet.sh` or add excutabel permission to `scripts/run_tasnet.sh` (like `chmod +x scripts/run_tasnet.sh`).

I think this is basic skills for Python and Shell and shouldn't be discussed here.
